### ISSUE TITLE
mysql怎么用？

### ISSUE THREAD

**Issue by googlechuang** [tpsmr/formwork#2]
mysql怎么用

**Comment by tpsmr** [comment]
https://github.com/tpsmr/formwork/blob/main/project/database/pysql.py

**Comment by tpsmr** [comment]
#-usage-########################################  
#-usage-########################################     
# formwork_mysql = MYSQL(host="1.1.1.1",user="root",pwd="formwork_password",db="formwork_db")
# result_list= formwork_mysql.ExecQuery("SELECT A,B,C FROM formwork_table_name")
# for ( A,B,C ) in result_list:
#     print A,B,C
# #增加
# formwork_mysql.ExecNonQuery( "insert into formwork_table_name(A,B,C) values('{0}','{1}','{2}')".format(u"aa",u"bb",u"cc") )
# #减少
# formwork_mysql.ExecNonQuery( '''delete from formwork_table_name where A like "{0}"'''.format(u",,") )
# #改
# formwork_mysql.ExecNonQuery( '''update formwork_table_name set {2} = "{3}" where {0}="{1}"'''.format(u"aa",u"bb","cc","dd") )

# result_list = formwork_mysql.ExecQuery("SELECT A,B,C FROM formwork_table_name")
# for ( A,B,C) in result_list:
#     print A,B,C
    
# formwork_mysql.Close()
#-usage-########################################
#-usage-########################################

**Comment by tpsmr** [comment]
https://github.com/tpsmr/formwork/blob/main/project/routes/index.py

**Comment by tpsmr** [comment]
```
@indexbp.route('/test/formwork', methods=('GET', 'POST'))
def test_formwork():
    getpostdict = t_f.s_r(request)
    g_p_d = getpostdict
    serial = t_f.g_s()
    g_p_d['serial'] = serial
    g_p_d['ip'] = request.remote_addr
    g_p_d['time'] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')
    print( p_c.db.secure(g_p_d['key']) )
    p_c.db.ExecNonQuery(s.t["formwork_sql"].format(formwork=p_c.db.secure(g_p_d['formwork'])))
    return render_template('formwork.html',formwork=formwork)
```

**Comment by aswallz** [comment]
https://github.com/aswallz/formwork/blob/main/project/database/pysql.py
